# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: azulbukh <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/02/22 18:48:39 by azulbukh          #+#    #+#              #
#    Updated: 2018/02/22 22:33:56 by azulbukh         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

DEST = ft_display_file

all:
	gcc main.c ft_putstr.c ft_putchar.c -I ft.h -o $(DEST)

clean:
	rm $(DEST)

fclean: clean

re: fclean all
