# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: azulbukh <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/02/22 17:43:26 by azulbukh          #+#    #+#              #
#    Updated: 2018/02/22 19:17:37 by azulbukh         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	gcc -c test.c ft_putchar.c ft_strlen.c ft_putnbr.c ft_putstr.c -I ft.h
	gcc *.o

clean:
	find . -name "*.o" -delete
	rm a.out

